CREATE PROC CREATEDATA
@VALUE AS INT
AS
BEGIN
	DECLARE @NAME AS VARCHAR(50), @SURNAME AS VARCHAR(50),@GENDER AS VARCHAR(10),@PHONENUMBER AS VARCHAR(50),
	@EMAIL1 AS INT, @EMAIL AS VARCHAR(50),@EMAIL2 AS INT, @EMAIL3 AS INT,@EMAIL4 AS  INT,
	@BIRTHDATE AS DATE,@AGE AS INT, @CITY AS VARCHAR(50), @ITEMCODE AS VARCHAR(30),
	@ITEMNAME AS VARCHAR(30), @UNITPRICE AS FLOAT , @AMOUNT AS INT, 
	@TOTALPRICE AS FLOAT,@PAYMENTTYPE AS INT,@SALETIME AS DATETIME ,@INVOICECODE AS uniqueidentifier,@N1 AS INT , 
	@N2 AS INT , @N3 AS INT,@N4 AS INT ,@N5 AS INT ,@N6 AS INT ,@N7 AS INT ,@N8 AS INT ,@N9 AS INT 
	DECLARE @I AS INT = 0
	DECLARE @ITEMCODE1 AS INT

	WHILE  @I < @VALUE
	BEGIN
		SELECT @NAME = NAME_,@GENDER = GENDER FROM NAMES WHERE ID = ROUND(RAND()*(611-1)+1,0)
		SELECT @SURNAME = SURNAME_ FROM SURNAMES WHERE ID = ROUND(RAND()*(1000-1)+1,0)
------------------
		SET @N1 = ROUND(RAND()*(999-100)+100,0)
		SET @N2 = ROUND(RAND()*(99-10)+10,0)
		SET @N3 = ROUND(RAND()*(99-10)+10,0)
		SET @N4 = ROUND(RAND()*(99-10)+10,0)
		SET @N5 = ROUND(RAND()*(99-10)+10,0)
		SET @N6 = ROUND(RAND()*(99-10)+10,0)
		SET @N7 = ROUND(RAND()*(99-10)+10,0)
		SET @N8 = ROUND(RAND()*(99-10)+10,0)
		SET @N9 = ROUND(RAND()*(99-10)+10,0)
		IF @N1 > 800 AND @N1 <999 
		BEGIN
			SET @PHONENUMBER = '(534)'+' '+CONVERT(varchar(20),@N1)+' '+CONVERT(varchar(20),@N2)+' '+CONVERT(varchar(20),@N3)
		END
		ELSE IF @N1 > 550 AND @N1 <750 
		BEGIN
			SET @PHONENUMBER = '(531)'+' '+CONVERT(varchar(20),@N1)+' '+CONVERT(varchar(20),@N4)+' '+CONVERT(varchar(20),@N5)
		END
		ELSE IF @N1 > 101 AND @N1 <450 
		BEGIN
			SET @PHONENUMBER = '(533)'+' '+CONVERT(varchar(20),@N1)+' '+CONVERT(varchar(20),@N6)+' '+CONVERT(varchar(20),@N7)
		END
		ELSE 
		BEGIN
			SET @PHONENUMBER = '(557)'+' '+CONVERT(varchar(20),@N1)+' '+CONVERT(varchar(20),@N8)+' '+CONVERT(varchar(20),@N9)
		END
-------------------		
		SET @EMAIL1 = ROUND(RAND()*(9999-1)+1,0)
		SET @EMAIL2 = ROUND(RAND()*(9999-1)+1,0)
		SET @EMAIL3 = ROUND(RAND()*(9999-1)+1,0)
		SET @EMAIL4 = ROUND(RAND()*(9999-1)+1,0)
		IF  @EMAIL2>7500 AND @EMAIL2<9000
			BEGIN
				SET @EMAIL = LOWER(SUBSTRING(@NAME,1,1))+'_'+LOWER(SUBSTRING(@SURNAME,1,LEN(@SURNAME)))+CONVERT(varchar(20),@EMAIL1)+'@gmail.com'
			END
		ELSE IF @EMAIL3 < 5000 AND @EMAIL3 > 1000
			BEGIN
				SET @EMAIL = LOWER(SUBSTRING(@NAME,1,1))+'_'+LOWER(SUBSTRING(@SURNAME,1,LEN(@SURNAME)))+CONVERT(varchar(20),@EMAIL1)+'@hotmail.com'
			END
		ELSE IF @EMAIL4 < 7500 AND @EMAIL4 > 5000
			BEGIN
				SET @EMAIL = LOWER(SUBSTRING(@NAME,1,1))+'_'+LOWER(SUBSTRING(@SURNAME,1,LEN(@SURNAME)))+CONVERT(varchar(20),@EMAIL1)+'@icloud.com'
			END
		ELSE	
			BEGIN
				SET @EMAIL = LOWER(SUBSTRING(@NAME,1,1))+'_'+LOWER(SUBSTRING(@SURNAME,1,LEN(@SURNAME)))+CONVERT(varchar(20),@EMAIL1)+'@outlook.com'
			END
------------------------
		SET @BIRTHDATE = DATEADD(DAY,ROUND(RAND()*18250,0) , '1955-01-01')
		SET @AGE = DATEDIFF(YEAR,@BIRTHDATE,GETDATE())
		SELECT @CITY = CITY FROM CITIES WHERE ID = ROUND(RAND()*(81-1)+1,0)
		--SELECT @ITEMCODE = ITEMCODE,@ITEMNAME = ITEMNAME FROM ITEMS WHERE ID = ROUND(RAND()*(1000-1)+1,0)
		SET @ITEMCODE1 = ROUND(RAND()*500,0)
		SET @ITEMCODE =  'URUN'+REPLICATE('0',8-LEN(@ITEMCODE1))+CONVERT(varchar(20),@ITEMCODE1)
		SET @ITEMNAME = 'URUN'+CONVERT(varchar(20),@ITEMCODE1)
		SET @UNITPRICE =  ROUND(RAND()*(50)+1,2)
		SET @AMOUNT =   ROUND(RAND()*(10-1)+1,0)
		SET @TOTALPRICE = @UNITPRICE * @AMOUNT
		SET @PAYMENTTYPE =   ROUND(RAND()*(2-1)+1,0)
		SET @SALETIME = DATEADD(SECOND,ROUND(RAND()*94608000,0) , '2020-01-01 00:00:00')
		SET @INVOICECODE =  NEWID()
		INSERT INTO SALES
		(NAMESURNAME,GENDER,PHONENUMBER,EMAIL,BIRTHDATE,AGE,CITY,ITEMCODE,ITEMNAME,UNITPRICE,AMOUNT,TOTALPRICE,PAYMENTTYPE,SALETIME,INVOICECODE)
		VALUES
		(@NAME+' '+@SURNAME,@GENDER,@PHONENUMBER,@EMAIL,@BIRTHDATE,@AGE,@CITY,@ITEMCODE,@ITEMNAME,@UNITPRICE,@AMOUNT,@TOTALPRICE,@PAYMENTTYPE,@SALETIME,@INVOICECODE)
	SET @I = @I + 1 
	END
END



 

